spring:
  application:
    name: interior-inventory

  # 資料來源設定（請依你的 Docker / 本機環境調整）
  datasource:
    url: jdbc:postgresql://localhost:5432/order_inventory_db
    username: order_user
    password: 123 #${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none    # 因為你已經用 schema.sql 建好表，這裡設 none
    show-sql: true      # 開發階段可以先開，方便看到 SQL
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

line:
  bot:
    channel-secret: 34e8de1c69d5b3bd6a3d18483445359b #${LINE_CHANNEL_SECRET:test}
    channel-token: rJK2HL1aYtT1o1GwnvmnRwtZSW2UAodGsLf5AqGZ4ML3/+9L/VbmPg4oNAr8HLoqgxB72xesB4L0y/ezCggpMVIVW1+dxO1pSG+WaeZb9J0wnOFmM033oF5xaVPjCkRIv/q/BnjX13wC1dvBM/A2kAdB04t89/1O/w1cDnyilFU= #${LINE_CHANNEL_TOKEN:test}
    handler:
      path: /webhook/line

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG      # 如果 SQL 太吵，可以改回 INFO
