server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # public-frontend 也需要打後端 API
    # location /api/ {
    #     proxy_pass http://app:8080/api/;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    # }
    location /api/ {
        proxy_pass http://interiorinventory-production.up.railway.app/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}